"""Logistics app constants."""

SOURCE_PLATFORM_SHOPIFY = "shopify"
SOURCE_PLATFORM_ECOMMERCE = "ecommerce"
SOURCE_PLATFORM_CHOICES = (
    (SOURCE_PLATFORM_SHOPIFY, "Shopify"),
    (SOURCE_PLATFORM_ECOMMERCE, "Ecommerce"),
)

PROCESSING_RECEIVED = "received"
PROCESSING_ROUTING = "routing"
PROCESSING_SHIPMENT_CREATED = "shipment_created"
PROCESSING_FULFILLED = "fulfilled"
PROCESSING_FAILED = "failed"
PROCESSING_STATE_CHOICES = (
    (PROCESSING_RECEIVED, "Awaiting fulfillment"),
    (PROCESSING_ROUTING, "Preparing shipment"),
    (PROCESSING_SHIPMENT_CREATED, "Ready to ship"),
    (PROCESSING_FULFILLED, "Fulfilled"),
    (PROCESSING_FAILED, "Fulfillment failed"),
)

LOGISTICS_STATUS_PENDING = "pending"
LOGISTICS_STATUS_PICKED_UP = "picked_up"
LOGISTICS_STATUS_IN_TRANSIT = "in_transit"
LOGISTICS_STATUS_OUT_FOR_DELIVERY = "out_for_delivery"
LOGISTICS_STATUS_DELIVERED = "delivered"
LOGISTICS_STATUS_FAILED_DELIVERY = "failed_delivery"
LOGISTICS_STATUS_RETURNED = "returned"
LOGISTICS_STATUS_CHOICES = (
    (LOGISTICS_STATUS_PENDING, "Label created"),
    (LOGISTICS_STATUS_PICKED_UP, "Picked up"),
    (LOGISTICS_STATUS_IN_TRANSIT, "In transit"),
    (LOGISTICS_STATUS_OUT_FOR_DELIVERY, "Out for delivery"),
    (LOGISTICS_STATUS_DELIVERED, "Delivered"),
    (LOGISTICS_STATUS_FAILED_DELIVERY, "Delivery failed"),
    (LOGISTICS_STATUS_RETURNED, "Returned"),
)

LOGISTICS_TERMINAL_STATUSES = frozenset(
    {
        LOGISTICS_STATUS_DELIVERED,
        LOGISTICS_STATUS_FAILED_DELIVERY,
        LOGISTICS_STATUS_RETURNED,
    }
)

STATUS_HISTORY_QUIQUP_WEBHOOK = "quiqup_webhook"
STATUS_HISTORY_QUIQUP_POLL = "quiqup_poll"
STATUS_HISTORY_ADMIN = "admin"
STATUS_HISTORY_SOURCE_CHOICES = (
    (STATUS_HISTORY_QUIQUP_WEBHOOK, "Quiqup webhook"),
    (STATUS_HISTORY_QUIQUP_POLL, "Quiqup poll"),
    (STATUS_HISTORY_ADMIN, "Admin"),
)

PIPELINE_STEP_ROUTE = "route"
PIPELINE_STEP_QUIQUP = "quiqup"
PIPELINE_STEP_FULFILL = "fulfill"
DEFAULT_PIPELINE_STEPS = [
    PIPELINE_STEP_ROUTE,
    PIPELINE_STEP_QUIQUP,
    PIPELINE_STEP_FULFILL,
]
