# Generated by Django 6.0.5 on 2026-05-21 09:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ecommerce', '0007_alter_checkoutpaymentsettings_allow_cod_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityFulfillmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city_name', models.CharField(db_index=True, help_text='City to match (case-insensitive). Use * for fallback.', max_length=128)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority.')),
                ('courier_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(help_text='Quiqup service_kind (e.g. partner_next_day).', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'City fulfillment rule',
                'verbose_name_plural': 'City fulfillment rules',
                'ordering': ['priority', 'city_name'],
            },
        ),
        migrations.CreateModel(
            name='CourierConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier_name', models.CharField(max_length=255, unique=True)),
                ('api_credentials', models.JSONField(blank=True, default=dict, help_text='Optional per-courier credentials (JSON).')),
                ('supported_cities', models.JSONField(blank=True, default=list, help_text='List of city names this courier supports. Empty = all cities.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Courier configuration',
                'verbose_name_plural': 'Courier configurations',
                'ordering': ['courier_name'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_domain', models.CharField(db_index=True, help_text='e.g. my-store.myshopify.com', max_length=255, unique=True)),
                ('access_token', models.TextField(help_text='Admin API access token')),
                ('webhook_secret', models.CharField(help_text='Shared secret for HMAC verification of Shopify webhooks', max_length=255)),
                ('api_version', models.CharField(default='2024-10', max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Shopify store',
                'verbose_name_plural': 'Shopify stores',
                'ordering': ['shop_name'],
            },
        ),
        migrations.CreateModel(
            name='FulfillmentConfiguration',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('auto_fulfill_enabled', models.BooleanField(default=True, help_text='Automatically create fulfillments after Quiqup shipment.')),
                ('cod_enabled', models.BooleanField(default=True, help_text='Treat pending-payment ecommerce orders as COD when applicable.')),
                ('tracking_sync_enabled', models.BooleanField(default=True, help_text='Push tracking updates to Shopify and ecommerce fulfillments.')),
                ('ingest_api_token', models.CharField(blank=True, help_text='Bearer token for POST /api/v1/logistics/orders/ingest/', max_length=255)),
                ('quiqup_webhook_secret', models.CharField(blank=True, help_text='Optional secret to verify Quiqup webhook signatures.', max_length=255)),
                ('max_retry_count', models.PositiveSmallIntegerField(default=5)),
                ('default_fallback_courier', models.ForeignKey(blank=True, help_text='Used when no city rule matches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='logistics.courierconfiguration')),
            ],
            options={
                'verbose_name': 'Fulfillment configuration',
                'verbose_name_plural': 'Fulfillment configuration',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('source_platform', models.CharField(choices=[('shopify', 'Shopify'), ('ecommerce', 'Ecommerce')], db_index=True, max_length=32)),
                ('external_order_id', models.CharField(db_index=True, max_length=64)),
                ('order_number', models.CharField(blank=True, db_index=True, max_length=64)),
                ('customer_payload', models.JSONField(blank=True, default=dict)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('city', models.CharField(blank=True, db_index=True, max_length=128)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('courier_name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('service_type', models.CharField(blank=True, max_length=64)),
                ('courier_override', models.CharField(blank=True, help_text='Admin override; takes precedence over city rules.', max_length=255)),
                ('quiqup_shipment_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tracking_url', models.URLField(blank=True, max_length=500)),
                ('shipment_status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned')], db_index=True, default='pending', max_length=32)),
                ('processing_state', models.CharField(choices=[('received', 'Received'), ('routing', 'Routing'), ('shipment_created', 'Shipment created'), ('fulfilled', 'Fulfilled'), ('failed', 'Failed')], db_index=True, default='received', max_length=32)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('last_celery_task_id', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('ecommerce_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logistics_shipments', to='ecommerce.order')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='logistics.shopifyconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed_delivery', 'Failed Delivery'), ('returned', 'Returned')], max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.shipment')),
            ],
            options={
                'verbose_name_plural': 'Shipment status history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_platform', models.CharField(choices=[('shopify', 'Shopify'), ('ecommerce', 'Ecommerce')], max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=128)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='logistics.shopifyconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['source_platform', 'external_order_id'], name='logistics_s_source__d81767_idx'),
        ),
    ]
