"""
Domain choice constants (values + ``*_CHOICES`` tuples).

**Convention:** Do not define choice tuples or string sentinel values on model classes.
Put them in ``ecommerce.constants.<domain>`` and import them into models (for
``choices=`` / ``default=``) and into serializers, services, tests, or storefront code.

Typical imports::

    from ecommerce.constants.checkout import CHECKOUT_STATUS_OPEN, ORDER_FINANCIAL_PAID
    from ecommerce.constants.fulfillment import (
        FULFILLMENT_STATUS_PARTIAL,
        FULFILLMENT_CREATE_SCOPE_COMPLETE,
        SHIPMENT_STATUS_SUCCESS,
    )
    from ecommerce.constants.product import PRODUCT_STATUS_ACTIVE
    from ecommerce.constants.discount import DISCOUNT_TYPE_PERCENTAGE

You may also import from this package (re-exports below).
"""

from ecommerce.constants.checkout import (
    CHECKOUT_STATUS_CANCELLED,
    CHECKOUT_STATUS_CHOICES,
    CHECKOUT_STATUS_COMPLETED,
    CHECKOUT_STATUS_OPEN,
    ORDER_FINANCIAL_CHOICES,
    ORDER_FINANCIAL_PAID,
    ORDER_FINANCIAL_PENDING,
)
from ecommerce.constants.discount import (
    DISCOUNT_TYPE_CHOICES,
    DISCOUNT_TYPE_FIXED_AMOUNT,
    DISCOUNT_TYPE_PERCENTAGE,
)
from ecommerce.constants.fulfillment import (
    FULFILLMENT_CREATE_SCOPE_CHOICES,
    FULFILLMENT_CREATE_SCOPE_COMPLETE,
    FULFILLMENT_CREATE_SCOPE_PARTIAL,
    FULFILLMENT_STATUS_CHOICES,
    FULFILLMENT_STATUS_FULFILLED,
    FULFILLMENT_STATUS_PARTIAL,
    FULFILLMENT_STATUS_UNFULFILLED,
    SHIPMENT_STATUS_CANCELLED,
    SHIPMENT_STATUS_CHOICES,
    SHIPMENT_STATUS_ERROR,
    SHIPMENT_STATUS_FAILURE,
    SHIPMENT_STATUS_IN_TRANSIT,
    SHIPMENT_STATUS_OPEN,
    SHIPMENT_STATUS_PENDING,
    SHIPMENT_STATUS_SUCCESS,
    SHIPMENT_TERMINAL_VOID_STATUSES,
)
from ecommerce.constants.product import (
    PRODUCT_PUBLISHED_SCOPE_CHOICES,
    PRODUCT_PUBLISHED_SCOPE_GLOBAL,
    PRODUCT_PUBLISHED_SCOPE_NONE,
    PRODUCT_PUBLISHED_SCOPE_WEB,
    PRODUCT_STATUS_ACTIVE,
    PRODUCT_STATUS_ARCHIVED,
    PRODUCT_STATUS_CHOICES,
    PRODUCT_STATUS_DRAFT,
)

__all__ = [
    "CHECKOUT_STATUS_CANCELLED",
    "CHECKOUT_STATUS_CHOICES",
    "CHECKOUT_STATUS_COMPLETED",
    "CHECKOUT_STATUS_OPEN",
    "DISCOUNT_TYPE_CHOICES",
    "DISCOUNT_TYPE_FIXED_AMOUNT",
    "DISCOUNT_TYPE_PERCENTAGE",
    "FULFILLMENT_CREATE_SCOPE_CHOICES",
    "FULFILLMENT_CREATE_SCOPE_COMPLETE",
    "FULFILLMENT_CREATE_SCOPE_PARTIAL",
    "FULFILLMENT_STATUS_CHOICES",
    "FULFILLMENT_STATUS_FULFILLED",
    "FULFILLMENT_STATUS_PARTIAL",
    "FULFILLMENT_STATUS_UNFULFILLED",
    "ORDER_FINANCIAL_CHOICES",
    "ORDER_FINANCIAL_PAID",
    "ORDER_FINANCIAL_PENDING",
    "PRODUCT_PUBLISHED_SCOPE_CHOICES",
    "PRODUCT_PUBLISHED_SCOPE_GLOBAL",
    "PRODUCT_PUBLISHED_SCOPE_NONE",
    "PRODUCT_PUBLISHED_SCOPE_WEB",
    "PRODUCT_STATUS_ACTIVE",
    "PRODUCT_STATUS_ARCHIVED",
    "PRODUCT_STATUS_CHOICES",
    "PRODUCT_STATUS_DRAFT",
    "SHIPMENT_STATUS_CANCELLED",
    "SHIPMENT_STATUS_CHOICES",
    "SHIPMENT_STATUS_ERROR",
    "SHIPMENT_STATUS_FAILURE",
    "SHIPMENT_STATUS_IN_TRANSIT",
    "SHIPMENT_STATUS_OPEN",
    "SHIPMENT_STATUS_PENDING",
    "SHIPMENT_STATUS_SUCCESS",
    "SHIPMENT_TERMINAL_VOID_STATUSES",
]
