'''
Django settings for settings project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
'''

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-88bw)(9bfs9jiie8fp&+%_065-yqpvs%i3m1hf9*7s1__t9_6q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Cross-origin requests with cookies/session (e.g. Vite dev server) require trusted Origin.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# Application definition
UNFOLD_ADMIN_UI_APP = [
    'unfold',  # before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    'unfold.contrib.forms',  # optional, if special form elements are needed
    'unfold.contrib.inlines',  # optional, if special inlines are needed
    'unfold.contrib.import_export',  # optional, if django-import-export package is used
    'unfold.contrib.guardian',  # optional, if django-guardian package is used
    'unfold.contrib.simple_history',  # optional, if django-simple-history package is used
    'unfold.contrib.location_field',  # optional, if django-location-field package is used
    'unfold.contrib.constance',  # optional, if django-constance package is used
]

INSTALLED_APPS = [
    'cloudinary',
    'cloudinary_storage',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

THIRD_PARTY_APPS = [
    'django_filters',
    'import_export',
    'rest_framework',
    'rest_framework_simplejwt',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'drf_spectacular',
    'django_celery_beat',
]
CUSTOM_APPS = ['ecommerce', 'logistics']
INSTALLED_APPS = UNFOLD_ADMIN_UI_APP + INSTALLED_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'settings.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'settings.wsgi.application'


def _load_env_file(path: Path) -> None:
    """Populate os.environ from a simple KEY=value file (no extra dependency)."""
    if not path.is_file():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        if not key or key in os.environ:
            continue
        val = val.strip().strip("'").strip('"')
        os.environ[key] = val


_load_env_file(BASE_DIR / ".env")


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# PostgreSQL by default (requires psycopg). For tests without Postgres:
#   DJANGO_USE_SQLITE=1 python manage.py test
_use_sqlite = os.environ.get("DJANGO_USE_SQLITE", "").lower() in ("1", "true", "yes")

if _use_sqlite:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "ecommerce"),
            "USER": os.environ.get("POSTGRES_USER", "ecommerce"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", "ecommerce"),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": int(os.environ.get("POSTGRES_CONN_MAX_AGE", "60")),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'

MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'ecommerce.pagination.ApiCursorPagination',
    'PAGE_SIZE': 20,
}

# django-allauth 65+ — email-only login/signup similar to Shopify staff accounts
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # use 'mandatory' in production with email backend

REST_AUTH = {
    'LOGIN_SERIALIZER': 'dj_rest_auth.serializers.LoginSerializer',
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'SESSION_LOGIN': False,
    'TOKEN_MODEL': None,
    'USER_DETAILS_SERIALIZER': 'dj_rest_auth.serializers.UserDetailsSerializer',
    'REGISTER_SERIALIZER': 'ecommerce.auth_serializers.ShopifyRegisterSerializer',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Ecommerce API',
    'COMPONENT_SPLIT_REQUEST': True,
    'AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
    },
}

from import_export.formats import base_formats

IMPORT_EXPORT_FORMATS = [
    fmt for fmt in (base_formats.CSV, base_formats.XLSX) if fmt.is_available()
]

# Shopify-style customer-facing order display (order_number + name, e.g. #1000).
ECOMMERCE_ORDER_NAME_PREFIX = os.environ.get("ECOMMERCE_ORDER_NAME_PREFIX", "#")
try:
    ECOMMERCE_FIRST_ORDER_NUMBER = int(os.environ.get("ECOMMERCE_FIRST_ORDER_NUMBER", "1000"))
except ValueError:
    ECOMMERCE_FIRST_ORDER_NUMBER = 1000

# Stripe Checkout (https://dashboard.stripe.com/apikeys)
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

# React + Vite storefront (Stripe redirect URLs generated when admin defaults are empty)
STOREFRONT_BASE_URL = os.environ.get("STOREFRONT_BASE_URL", "http://localhost:5173")
STOREFRONT_CHECKOUT_SUCCESS_PATH = os.environ.get(
    "STOREFRONT_CHECKOUT_SUCCESS_PATH",
    "/checkout/success",
)
STOREFRONT_CHECKOUT_CANCEL_PATH = os.environ.get(
    "STOREFRONT_CHECKOUT_CANCEL_PATH",
    "/checkout/cancel",
)

import cloudinary

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'de3gkz0tv',
    'API_KEY': '826458878376117',
    'API_SECRET': 'Xym0FcNAFpFkMNITzjkCXji5Lqc',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STORAGES = {
    'default': {
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
}

# Logistics / Quiqup / Celery (Shopify credentials are admin-managed only)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
QUIQUP_USE_MOCK = os.environ.get('QUIQUP_USE_MOCK', '').lower() in ('1', 'true', 'yes')
QUIQUP_BASE_URL = os.environ.get('QUIQUP_BASE_URL', '')
QUIQUP_CLIENT_ID = os.environ.get('QUIQUP_CLIENT_ID', '')
QUIQUP_CLIENT_SECRET = os.environ.get('QUIQUP_CLIENT_SECRET', '')
QUIQUP_API_KEY = os.environ.get('QUIQUP_API_KEY', '')
LOGISTICS_QUIQUP_POLL_MINUTES = int(os.environ.get('LOGISTICS_QUIQUP_POLL_MINUTES', '15'))

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_DEFAULT_QUEUE = 'logistics'
CELERY_TASK_ROUTES = {
    'logistics.*': {'queue': 'logistics'},
}
CELERY_BEAT_SCHEDULE = {
    'poll-quiqup-tracking': {
        'task': 'logistics.poll_quiqup_tracking_batch',
        'schedule': LOGISTICS_QUIQUP_POLL_MINUTES * 60,
    },
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'logistics': {'handlers': ['console'], 'level': 'INFO'},
        'logistics.tasks': {'handlers': ['console'], 'level': 'INFO'},
        'logistics.quiqup': {'handlers': ['console'], 'level': 'INFO'},
    },
}
