# Generated by Django 6.0.5 on 2026-05-14 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='size_chart', to='ecommerce.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SizeChartColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='ecommerce.sizechart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SizeChartRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ecommerce.sizechart')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SizeChartCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ecommerce.sizechart')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ecommerce.sizechartcolumn')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='ecommerce.sizechartrow')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='sizechartcolumn',
            constraint=models.UniqueConstraint(fields=('chart', 'sort_order'), name='size_chart_column_unique_chart_sort'),
        ),
        migrations.AddConstraint(
            model_name='sizechartrow',
            constraint=models.UniqueConstraint(fields=('chart', 'sort_order'), name='size_chart_row_unique_chart_sort'),
        ),
        migrations.AddConstraint(
            model_name='sizechartcell',
            constraint=models.UniqueConstraint(fields=('chart', 'row', 'column'), name='size_chart_cell_unique_chart_row_column'),
        ),
    ]
