# Generated by Django 6.0.5 on 2026-05-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_size_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Checkout Session id (cs_…) while payment is in progress.', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent id (pi_…) after successful payment.', max_length=255),
        ),
    ]
