# Generated by Django 6.0.5 on 2026-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_stripe_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPaymentSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('stripe_checkout_enabled', models.BooleanField(default=True, help_text='Allow Stripe Checkout for paid carts when STRIPE_SECRET_KEY is set in the environment.')),
                ('allow_manual_complete', models.BooleanField(default=False, help_text='When enabled, the API allows POST /checkouts/{id}/complete/ without Stripe even when the total is greater than zero (e.g. phone orders, testing).')),
                ('default_success_url', models.URLField(blank=True, help_text='Default Stripe success redirect if the storefront omits success_url. Must include {CHECKOUT_SESSION_ID}.', max_length=500)),
                ('default_cancel_url', models.URLField(blank=True, help_text='Default Stripe cancel redirect if the storefront omits cancel_url.', max_length=500)),
                ('checkout_payment_note', models.TextField(blank=True, help_text='Internal note for staff (not exposed on the storefront API).')),
            ],
            options={
                'verbose_name': 'Checkout payment settings',
                'verbose_name_plural': 'Checkout payment settings',
            },
        ),
    ]
