# Generated by Django 6.0.5 on 2026-05-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_rename_manual_to_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutpaymentsettings',
            name='allow_cod_complete',
            field=models.BooleanField(default=False, help_text='When enabled, customers can place paid orders via POST /checkouts/{id}/complete/ without Stripe (financial_status: pending).', verbose_name='Allow cash on delivery (COD)'),
        ),
        migrations.AlterField(
            model_name='checkoutpaymentsettings',
            name='stripe_checkout_enabled',
            field=models.BooleanField(default=True, help_text='Allow Stripe Checkout for paid carts. Also set STRIPE_SECRET_KEY and STRIPE_PUBLISHABLE_KEY in ecommerce/.env (see .env.example).'),
        ),
    ]
